-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 2,
    },
    input = {
        kb_layout = "us,ua",
        kb_options = "",
        kb_variant = ",winkeysenhanced",
    },
})
